#gimmeproxy_url: "http://gimmeproxy.com/api/getProxy?anonymityLevel=1&country=CN&user-agent=true&supportsHttps=true&timeout=60&maxCheckPeriod=6000&protocol=http"
gimmeproxy_url: "http://gimmeproxy.com/api/getProxy?anonymityLevel=1&supportsHttps=true&timeout=60&maxCheckPeriod=6000&protocol=http"
#gimmeproxy_url: "http://gimmeproxy.com/api/getProxy?anonymityLevel=1&user-agent=true&supportsHttps=true&timeout=60&maxCheckPeriod=6000&protocol=http"
g_spreadsheet_url: "https://docs.google.com/spreadsheets/d/1hAWBxpWmIBvP23GOBiVjgpmWXM3Q_6ShBAayllBUjZk/pub?output=tsv"
ip_info_url: "http://ip-api.com/json"
referer_url: "http://weibo.com/u/2957260672?topnav=1&wvr=6&topsug=1&is_all=1"
tor_proxy: "104.131.169.20:5566"
